"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6l(68d@h&-=&@f7fd4l_$nbt#(@37=e0c-&sa_ii#b9c8i^=cr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'users',
    'crispy_forms',
    'crispy_bootstrap5',
    'gmailapi_backend',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'blog-home'
LOGIN_URL = 'login'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'piyusvijay1947@gmail.com'
# EMAIL_HOST_PASSWORD = 'lfzt fmjf tbot tpbi'

# EMAIL_BACKEND = 'mailjet_backend.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'in-v3.mailjet.com'
# EMAIL_HOST = 'smtp.mailjet.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# MAILJET_API_KEY = '651ef03f278e37b9404d3ef78e67360d'  
# MAILJET_API_SECRET = '61d0e55e2bc98c9434fafd840ae12e93'

EMAIL_BACKEND = 'gmailapi_backend.mail.GmailBackend'
GMAIL_API_CLIENT_ID = '13735081034-he8a3f3g1rc5lrvadt7vrkri8khgrk7l.apps.googleusercontent.com'
GMAIL_API_CLIENT_SECRET = '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'
GMAIL_API_REFRESH_TOKEN = 'refresh_token'

# 13735081034-he8a3f3g1rc5lrvadt7vrkri8khgrk7l.apps.googleusercontent.com

# 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


# gmail_oauth2 --generate_oauth2_token \
#   --client_id="13735081034-he8a3f3g1rc5lrvadt7vrkri8khgrk7l.apps.googleusercontent.com" \
#   --client_secret="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" \
#   --scope="https://www.googleapis.com/auth/gmail.send"

# gmail_oauth2 --generate_oauth2_token --client_id="13735081034-he8a3f3g1rc5lrvadt7vrkri8khgrk7l.apps.googleusercontent.com" --client_secret="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" --scope="https://www.googleapis.com/auth/gmail.send"
